// this file is not to be explicitly included in project.
    #include <QFileDialog>
    #include <QPushButton>
    #include <QLabel>
    #include <QCheckBox>
    #include <QComboBox>
    #include <QVBoxLayout>
    #include <QHBoxLayout>
    #include <QDrag>
    #include <QMimeData>
    #include <QToolButton>
    #include <QFrame>
    #include <QValidator>
    #include <QAction>
    #include <QButtonGroup>
    #include <QHeaderView>
    #include <QLineEdit>
    #include <QSpacerItem>
    #include <QStackedWidget>
    #include <QRadioButton>
    #include <QTabWidget>
    #include <QToolTip>
    #include <QMouseEvent>
    #include <QStyle>
    #include <QTimer>

    #include <QApplication>
    #include <QVariant>
    #include <QMap>
    #include <QVector>
    #include <QStringList>
    #include <QDir>
    #include <QPointer>
    #include <QColor>

    #include <string>
    #include <set>
    #include <map>
    #include <memory>
    #include <vector>
    #include <bitset>
    #include <functional>
    #include <algorithm>
    #include <numeric>
    #include <iterator>
    #include <cmath>
    #include <cassert>
    #include <cfloat>
    #include <complex>
    #include <cstddef>
    #include <cstdlib>